[home-router]
    enabled = True
    hostname = %%MKTXP_HOST%%
    port = %%MKTXP_PORT%%
    username = %%MKTXP_USER%%
    password = %%MKTXP_PASS%%

    use_ssl = False
    no_ssl_certificate = False
    ssl_certificate_verify = False

    dhcp = True
    pool = True
    interface = True
    firewall = True
    monitor = True
    route = True
    wireless = False
    capsman = False
    kid_control_device = False

    netwatch = True
    public_ip = True
    health = True
    queue = True
    connection = True
