MONITOR eaton@localhost 1 upsmon %%NUT_UPSMON_PASS%% primary

MINSUPPLIES 1
SHUTDOWNCMD "/home/aarzner/home-infra/pi-control/ups/shutdown-cluster.sh"
POWERDOWNFLAG /etc/killpower

POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 25
RBWARNTIME 43200
NOCOMMWARNTIME 600
FINALDELAY 5
